AL_VIDEO_STREAM_CONST = {
  ICOSAHEDRON_RADIUS: 120
  SURFACE_Y: - 120
  SURFACE_DISTANCE_KOEFFICIENT: 0.4

  ##
  # ENUMS
  # - VIDEO MODE
  # NO_VIDEO: 0
  NO_VIDEO: 'none'
  # RGB_VIDEO: 1
  RGB_VIDEO: '2d'
  # DEPTH_VIDEO: 2
  DEPTH_VIDEO: '3d'
}

module.exports = AL_VIDEO_STREAM_CONST
